language: java
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_script:
  - mysql -u root -e 'create database IF NOT EXISTS purely;'
  - mysql -u root -e 'create table purely.USER (id INT, username VARCHAR(50), password VARCHAR(50), role VARCHAR(20), enabled boolean);'
script: ./gradlew test --info
